repos:
- repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        args: [ --cov=qftools ]

-   repo: https://github.com/python-poetry/poetry
    rev: 1.8.4
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
    -   id: poetry-install

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.8.5
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
