repos:
- repo: local
  hooks:
  - id: pytest-check
    name: pytest-check
    entry: pytest
    language: system
    pass_filenames: false
    always_run: true

- repo: local
  hooks:
  - id: ruff
    name: ruff
    description: "Run 'ruff' for extremely fast Python linting"
    entry: ruff check --force-exclude
    language: python
    types_or: [python, pyi, jupyter]
    args: []
    require_serial: true
    additional_dependencies: []
    minimum_pre_commit_version: "2.9.2"

  - id: ruff-format
    name: ruff-format
    description: "Run 'ruff format' for extremely fast Python formatting"
    entry: ruff format --force-exclude
    language: python
    types_or: [python, pyi, jupyter]
    args: []
    require_serial: true
    additional_dependencies: []
    minimum_pre_commit_version: "2.9.2"

- repo: local
  hooks:
  - id: poetry-check
    name: poetry-check
    description: run poetry check to validate config
    entry: poetry check
    language: python
    pass_filenames: false
    files: ^(.*/)?(poetry\.lock|pyproject\.toml)$

  - id: poetry-lock
    name: poetry-lock
    description: run poetry lock to update lock file
    entry: poetry lock
    language: python
    pass_filenames: false
    files: ^(.*/)?(poetry\.lock|pyproject\.toml)$

  - id: poetry-install
    name: poetry-install
    description: run poetry install to install dependencies from the lock file
    entry: poetry install
    language: python
    pass_filenames: false
    stages: [post-checkout, post-merge]
    always_run: true
